(function(){'use strict';
const ENDPOINT='https://forms.mavorealestate.com/public/branded-shares/';
function tokenFromHash(hash){return /^#[A-Za-z0-9_-]{32}$/.test(hash)?hash.slice(1):''}
function safeImages(values){if(!Array.isArray(values))return [];return values.filter(value=>{if(typeof value!=='string'||value.length>2000||/[\x00-\x20\\]/.test(value)||value.includes('%')||/\/\.\.?\//.test(value))return false;try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='forms.mavorealestate.com'&&!u.username&&!u.password&&!u.hash&&!u.search&&(!u.port||u.port==='443')&&/^\/public\/branded-shares\/[A-Za-z0-9_-]{32}\/media\/[a-f0-9]{64}$/.test(u.pathname)}catch{return false}}).slice(0,51)}
function leaseMs(data,elapsed){const duration=Date.parse(data.expires_at)-Date.parse(data.verified_at);return Number.isFinite(duration)?Math.max(0,Math.min(60000,duration)-Math.max(0,elapsed)):0}
if(typeof module!=='undefined'&&module.exports)module.exports={tokenFromHash,safeImages,leaseMs};
if(typeof document==='undefined')return;
const $=s=>document.querySelector(s);let generation=0,controller=null,timer=null,expiryTimer=null,galleryPhotos=[],galleryIndex=0;
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function clear(){generation++;if(controller)controller.abort();controller=null;clearTimeout(timer);clearTimeout(expiryTimer);$('#properties').replaceChildren();$('#collection-meta').hidden=true;galleryPhotos=[];$('#gallery-image').replaceChildren();if($('#gallery').open)$('#gallery').close()}
function status(title,copy,retry=false){$('#status-panel').hidden=false;$('#status-title').textContent=title;$('#status-copy').textContent=copy;$('#retry').hidden=!retry}
function photo(url,alt){const img=node('img');img.crossOrigin='anonymous';img.referrerPolicy='no-referrer';img.src=url;img.alt=alt;img.loading='lazy';img.addEventListener('error',()=>{img.replaceWith(node('span','התמונה אינה זמינה כרגע'))},{once:true});return img}
function showPhoto(){const host=$('#gallery-image');host.replaceChildren();if(galleryPhotos.length){host.append(photo(galleryPhotos[galleryIndex],'תמונה '+(galleryIndex+1)+' של הדירה'));$('#image-position').textContent=(galleryIndex+1)+' / '+galleryPhotos.length}}
function render(data){if(!Array.isArray(data.listings)||data.listings.length>100)throw Error('invalid');const host=$('#properties');for(const row of data.listings){const card=node('article',undefined,'property-card'),cover=node('div',undefined,'cover'),images=safeImages(row.images),title=[row.neighborhood,row.city].filter(v=>typeof v==='string'&&v).join(', ')||'פרטי מיקום לא נמסרו';if(images.length){cover.append(photo(images[0],'תמונת הדירה באזור '+title));const button=node('button',images.length+' תמונות','photo-button');button.type='button';button.setAttribute('aria-label','פתיחת תמונות — '+title);button.onclick=()=>{galleryPhotos=images;galleryIndex=0;$('#gallery-title').textContent=title;showPhoto();$('#gallery').showModal()};cover.append(button)}else cover.append(node('span','לא נמסרו תמונות'));const body=node('div',undefined,'property-body');body.append(node('h3',title),node('p','מיקום כללי · פרטים מדויקים מול המשרד','location-note'));if(typeof row.price==='number'&&Number.isFinite(row.price)){const price=node('p','₪'+row.price.toLocaleString('he-IL'),'price');if(row.deal_type==='rent')price.append(node('small',' / חודש'));body.append(price)}const facts=node('div',undefined,'facts');if(row.property_type)facts.append(node('span',row.property_type));if(typeof row.rooms==='number')facts.append(node('span',row.rooms+' חדרים'));if(typeof row.size==='number')facts.append(node('span',row.size+' מ״ר'));if(facts.children.length)body.append(facts);const amenities=node('div',undefined,'amenities');for(const [key,label]of Object.entries({parking:'חניה',elevator:'מעלית',balcony:'מרפסת',safe_room:'ממ״ד'})){if(row[key]===true)amenities.append(node('span',label,'amenity'))}body.append(amenities);card.append(cover,body);host.append(card)}$('#count').textContent=data.listings.length+' דירות באוסף';$('#checked').textContent='הזמינות נבדקה עכשיו';$('#collection-meta').hidden=false;$('#status-panel').hidden=data.listings.length>0;if(!data.listings.length)status('כרגע אין דירות זמינות באוסף','נשמח לבדוק עבורכם אפשרויות נוספות.');}
async function load(){clear();if(document.hidden){status('האוסף מושהה','בודקים מחדש כשתחזרו לעמוד.');return}const token=tokenFromHash(location.hash);if(!token){status('הקישור אינו תקין','בדקו שהעתקתם את הקישור המלא שנשלח אליכם.');return}if(navigator.onLine===false){status('אין חיבור לרשת','כדי לראות דירות עדכניות נדרש חיבור לרשת.',true);return}const own=generation,start=performance.now(),abort=new AbortController();controller=abort;const timeout=setTimeout(()=>abort.abort(),15000);status('בודקים את האוסף…','מאמתים את תוקף הקישור ואת זמינות הדירות.');try{const response=await fetch(ENDPOINT+token,{credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer',signal:abort.signal,redirect:'error'});const data=await response.json();if(own!==generation||document.hidden)return;if(!response.ok){const closed=[404,410].includes(response.status);status(closed?'השיתוף אינו פעיל':'האוסף אינו זמין כרגע',closed?'השיתוף הסתיים, בוטל או שהקישור אינו תקין. אפשר לבקש מהמשרד קישור חדש.':'לא ניתן לאמת את המקור כרגע. הדירות אינן מוצגות עד שהחיבור יחזור.',!closed);return}const lease=leaseMs(data,performance.now()-start);if(lease<=0){status('השיתוף הסתיים','אפשר לבקש מהמשרד קישור חדש.');return}render(data);expiryTimer=setTimeout(()=>{clear();status('מאמתים שוב את האוסף','המידע הוסתר עד לבדיקה חוזרת.',true);load()},lease);timer=setTimeout(load,Math.min(45000,lease));}catch(error){if(own===generation){clear();status('האוסף אינו זמין כרגע','לא ניתן לאמת את המידע. נסו שוב בעוד כמה רגעים.',true)}}finally{clearTimeout(timeout)}}
$('#retry').onclick=load;$('#gallery-close').onclick=()=>$('#gallery').close();$('#gallery').addEventListener('close',()=>{$('#gallery-image').replaceChildren();galleryPhotos=[]});$('#previous').onclick=()=>{if(galleryPhotos.length){galleryIndex=(galleryIndex-1+galleryPhotos.length)%galleryPhotos.length;showPhoto()}};$('#next').onclick=()=>{if(galleryPhotos.length){galleryIndex=(galleryIndex+1)%galleryPhotos.length;showPhoto()}};
document.addEventListener('visibilitychange',()=>{if(document.hidden){clear();status('האוסף מושהה','בודקים מחדש כשתחזרו לעמוד.')}else load()});window.addEventListener('offline',()=>{clear();status('אין חיבור לרשת','הדירות הוסתרו עד שאפשר יהיה לאמת את המידע.',true)});window.addEventListener('online',load);window.addEventListener('hashchange',load);window.addEventListener('pagehide',clear);window.addEventListener('pageshow',event=>{if(event.persisted)load()});load();
})();
